### PR TITLE
fix/add linters

### LINKED ISSUE #2: Adding security tooling
Caches are a bit of a mine field, security wise. I would gladly contribute.

I would think that adding `gosec` and `govet` probably makes sense. The codebase might also benefit from the larger `golangci-lint` package. Would you be open to a PR that introduces these?

### PR DESCRIPTION
**Pull request by audunmo**
Fixes #2 

Adds the gosec and govet linters, to help ensure that the package isn't inadvertently introducing vulnerabilites to the consuming software.

I also took the liberty of adding the `performance` and `bugs` presets, since this package prides itself on being fast. The `prealloc` linter highlighted two slice assignments that could benefit from length preallocation, as their final size is known ahead of time. 

On a general basis, I'd advise turning on the `gofumpt` linter as well, so that you can easily enforce code-style going forward. However, running it produces a large diff right now, so that should rather be its own separate PR, if and when the need arises.

Looking forward to following the development of this project :)

### CODE REVIEW

File: nocache/search.go [hunk 1]
```diff
@@ -67,7 +67,7 @@ func (ft *FullText) search(sp SearchParams) []map[string]any {
 
 	// Variables for storing the smallest words array
 	var (
-		smallest      int = 0
+		smallest      int = 0 //nolint:ineffassign
```
Comment (audunmo) [inline nocache/search.go:70]: I ignore these, as they're inoffensive, and it imo looks a bit weird to just declare the type. Maybe I'm not enough of a hardcore gopher yet 🤓

**Review by realTristan — APPROVED** [review]
